name: Android Build (Smaller APK)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet  # فقط flet، لا تستخدم requirements.txt إن لم تكن ضرورية

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Smaller APK (arm64 only)
        run: |
          flutter config --no-analytics
          flet build apk \
            --target-platform=android-arm64 \
            --build-number=${{ env.BUILD_NUMBER }} \
            --build-version=${{ env.BUILD_VERSION }} \
            --release

      - name: Upload Smaller APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-arm64.apk
          path: build/apk/app-release.apk
          if-no-files-found: error
          overwrite: true
